#version = "Two"
#use_small_heuristics = "Max"
#merge_derives = false
error_on_line_overflow = true
error_on_unformatted = true
style_edition = "2024"
max_width = 100
ignore = ["/build/", "/*-build/", "/build-*/", "/vendor/", "tests"]
