#!/bin/sh

[ -e /etc/containers/nodocker ] || \
  echo "Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg." >&2

# https://mywiki.wooledge.org/BashFAQ/073
exec /usr/bin/podman ${1+"$@"}
